openapi: 3.1.0
info:
  version: 1.0.0
  title: Image Super-Resolution API
  description: >-
    Image Super-Resolution API
servers:
  - url: http://localhost:8080
tags:
  - name: health
  - name: images
paths:
  /health:
    get:
      description: >
        Health check
      operationId: healthCheck
      tags:
        - health
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OK

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /images/upload:
    post:
      description: >
        Upload an image and launch a batch to increase the resolution
      operationId: uploadImage
      tags:
        - images
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/History"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          example: unexpected error

    History:
      type: object
      properties:
        historyID:
          type: integer
          example: 1
        timestamp:
          type: string
        isrJobID:
          type: string
          example: uuid
        status:
          type: string
          example: pending
