openapi: 3.1.0
info:
  version: 1.0.0
  title: Image Super-Resolution API
  description: >-
    Image Super-Resolution API
servers:
  - url: http://localhost:8080
tags:
  - name: health
  - name: images
  - name: histories
paths:
  /health:
    get:
      description: >
        Health check
      operationId: healthCheck
      tags:
        - health
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OK

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /images/upload:
    post:
      description: >
        Upload an image and launch a batch to increase the resolution
      operationId: uploadImage
      tags:
        - images
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/History"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /images/{jobID}:
    get:
      description: >
        Download an super resolution image
      operationId: downloadImage
      parameters:
        - name: jobID
          in: path
          required: true
          description: ID of the job to download
          schema:
            type: string
            example: e170b150-135f-4e50-96c8-2113dcfe4b3d
            format: uuid
      tags:
        - images
      responses:
        200:
          description: OK response
          content:
            image/*: {}
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  /histories:
    get:
      description: >
        Get histories
      operationId: listHistories
      tags:
        - histories
      parameters:
        - name: limit
          in: query
          description: Maximum number to retrieve at once
          schema:
            type: integer
        - name: offset
          in: query
          description: Offset when retrieving
          schema:
            type: integer
        - name: latest
          in: query
          description: Get only latest histories
          schema:
            type: boolean
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListHistoriesResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          example: unexpected error

    History:
      type: object
      properties:
        historyID:
          type: integer
          example: 1
        timestamp:
          type: string
          example: 2023-12-31 17:38:26.30918 +0000 UTC
        isrJobID:
          type: string
          format: uuid
          example: e170b150-135f-4e50-96c8-2113dcfe4b3d
        status:
          type: string
          example: pending

    ListHistoriesResponse:
      type: object
      properties:
        histories:
          type: array
          items:
            $ref: "#/components/schemas/History"
        hasNext:
          type: boolean
